version: 2.1

orbs:
  slack: circleci/slack@4.1

workflows:
  deploy:
    jobs:
      - deploy
      - notify:
          context:
            - slack-derycka
          requires:
            - deploy

jobs:

  deploy:
    machine: true
    resource_class: midnightideas/outerman
    steps:
      - checkout
      - run:
          name: 'Reveal git secret'
          command: 'git secret reveal -f'
      - run:
          name: 'Build dist'
          command: './bin/build'
      - run:
          name: 'Upload to server'
          command: './bin/deploy'

  notify:
    machine: true
    resource_class: midnightideas/outerman
    steps:
      - slack/notify:
          event: fail
          channel: cicd
          template: basic_fail_1
      - slack/notify:
          event: pass
          channel: cicd
          template: success_tagged_deploy_1
