version: 2.1

orbs:
  slack: circleci/slack@4.5

workflows:
  deploy:
    jobs:
      - deploy:
          context:
            - slack

jobs:
  deploy:
    machine: true
    resource_class: midnightideas/outerman
    steps:
      - checkout
      - run:
          name: "Reveal git secret"
          command: "git secret reveal -f"
      - run:
          name: "Build dist"
          command: "./bin/build"
      - run:
          name: "Commit to Github"
          command: "./bin/deploy"
      - slack/notify:
          event: fail
          channel: cicd
          template: basic_fail_1
